### PR TITLE
[WIP] Feat: implement planner by using LP solver

### PR DESCRIPTION
**Pull request by frantw**
# Description
Attempt to use an LP solver for strategy optimization.

# Changes
1. Get use of [yalps](https://www.npmjs.com/package/yalps)
2. Add `drops.json` and `formulas.json` data into the store
    - The drop data for the level reports is copied from [here](https://www.kdocs.cn/l/cd5MWeCl5bKw) , referencing from the version before v1.4
    - The highest drop stage for lower tier materials is referenced from [PRYDWEN.GG](https://www.prydwen.gg/re1999/guides/insight-cheat-sheet/)
3. Implement the `getSolve` function to use the LP solver for calculation
    - Consider material crafting as a type of drop and include it in the constraints (with the target material having a drop of 1 and the consumed materials having a drop of -1)

# TODOs
- [x] Remove the drop data with lower reported counts
- [x] Consider the warehouse inventory.
- [ ] Convert the result to an integer
       We exclude the stage variables so need to manually convert the stage count to integer in the solve result 
- [ ] Integrate with card/list on UI

# How to Test
Install dependencies by `npm i` before run the dev server.

I have temporarily printed out the plan results, which can be tested and verified through the console.

screenshots

The `result` here represents the activity spent.

# Something to Say
I haven't written Vue 3 before 😅
Also unsure if it's a good idea to directly modify existing code/data, so I've written most of the changes separately 

If you have any ideas or suggestions, please feel free to tell me.

### CODE REVIEW

**Comment by frantw** [comment]
Hi @windbow27, I wrote a strategy optimization demo by using an LP solver. 
I'll keep tweaking it, but feel free to review whenever you're available.

**Comment by windbow27** [comment]
Hello @frantw, I struggled a lot trying to implement a solution ;')
I was in the process of reviewing as you speak. Looks good, thank you so much 💯

**Comment by windbow27** [comment]
@frantw what's your discord? I want to discuss further.

**Comment by frantw** [comment]
> @frantw what's your discord? I want to discuss further.

My discord Id is `shadowbr1nger`, and glad to help!
I was just about to DIY my own game planner when I found your repo XD

**Pull request merged**
